baseurl = "http://inspiring-lichterman-2b0a36.netlify.com/"
title = "DCM"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "David C. Martin"
googleAnalytics = "XXX"

[Author]
    name = "DCM"
    profile = ""

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "David C. Martin"
    description = "A place for some of my past work"
    github = "https://github.com/dcldmartin"
    email = "info@davidcmart.in"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = ":slug/"

[[menu.main]]
    name = "Things"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2